<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="uk.ac.sheffield.com1003.cafe.TestServeNonexistentOrder" tests="1" skipped="0" failures="1" errors="0" timestamp="2024-03-18T23:00:34" hostname="Ruizhens-MacBook-Pro.local" time="0.0">
  <properties/>
  <testcase name="serveNonexistentOrder" classname="uk.ac.sheffield.com1003.cafe.TestServeNonexistentOrder" time="0.0">
    <failure message="java.lang.NullPointerException" type="java.lang.NullPointerException">java.lang.NullPointerException
	at uk.ac.sheffield.com1003.cafe.Recipe.addIngredient(Recipe.java:35)
	at uk.ac.sheffield.com1003.cafe.TestServeNonexistentOrder.createEspressoRecipe(TestServeNonexistentOrder.java:43)
	at uk.ac.sheffield.com1003.cafe.TestServeNonexistentOrder.serveNonexistentOrder(TestServeNonexistentOrder.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
